// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.21.0

package querytest

import (
	"time"
)

type Item struct {
	ID          int64      `json:"id"`
	JobID       int64      `json:"job_id"`
	Title       string     `json:"title"`
	PublishedAt *time.Time `json:"published_at"`
	CreatedAt   time.Time  `json:"created_at"`
}
