// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.21.0
// source: query.sql

package querytest

import (
	"context"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"sync"
	"time"

	"github.com/rs/zerolog/log"
)

const listItemsByJobIDsWithPerJobLimit = `-- name: ListItemsByJobIDsWithPerJobLimit :many
WITH ranked AS (
    SELECT id, job_id, title, published_at, created_at,
           COALESCE(published_at, created_at) AS sort_time,
           ROW_NUMBER() OVER (PARTITION BY job_id ORDER BY COALESCE(published_at, created_at) DESC, id DESC) AS rn
    FROM items
    WHERE job_id = ANY($2::bigint[])
)
SELECT id, job_id, title, published_at, created_at, sort_time
FROM ranked
WHERE rn <= $1
ORDER BY sort_time DESC, id DESC
`

type ListItemsByJobIDsWithPerJobLimitParams struct {
	LimitPerJob int64
	JobIds      []int64
}

type ListItemsByJobIDsWithPerJobLimitRow struct {
	ID          int64
	JobID       int64
	Title       string
	PublishedAt *time.Time
	CreatedAt   time.Time
	SortTime    time.Time
}

// -- timeout: 2s
func (q *Queries) ListItemsByJobIDsWithPerJobLimit(ctx context.Context, arg ListItemsByJobIDsWithPerJobLimitParams) ([]ListItemsByJobIDsWithPerJobLimitRow, error) {
	return _ListItemsByJobIDsWithPerJobLimit(ctx, q.AsReadOnly(), arg)
}

func (q *ReadOnlyQueries) ListItemsByJobIDsWithPerJobLimit(ctx context.Context, arg ListItemsByJobIDsWithPerJobLimitParams) ([]ListItemsByJobIDsWithPerJobLimitRow, error) {
	return _ListItemsByJobIDsWithPerJobLimit(ctx, q, arg)
}

func _ListItemsByJobIDsWithPerJobLimit(ctx context.Context, q CacheQuerierConn, arg ListItemsByJobIDsWithPerJobLimitParams) ([]ListItemsByJobIDsWithPerJobLimitRow, error) {
	qctx, cancel := context.WithTimeout(ctx, time.Millisecond*2000)
	defer cancel()
	q.GetConn().CountIntent("querytest.ListItemsByJobIDsWithPerJobLimit")
	rows, err := q.GetConn().WQuery(qctx, "querytest.ListItemsByJobIDsWithPerJobLimit", listItemsByJobIDsWithPerJobLimit, arg.LimitPerJob, arg.JobIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListItemsByJobIDsWithPerJobLimitRow
	for rows.Next() {
		var i *ListItemsByJobIDsWithPerJobLimitRow = new(ListItemsByJobIDsWithPerJobLimitRow)
		if err := rows.Scan(
			&i.ID,
			&i.JobID,
			&i.Title,
			&i.PublishedAt,
			&i.CreatedAt,
			&i.SortTime,
		); err != nil {
			return nil, err
		}
		items = append(items, *i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}

	return items, err
}

//// auto generated functions

func (q *Queries) Dump(ctx context.Context, beforeDump ...BeforeDump) ([]byte, error) {
	sql := "SELECT id,job_id,title,published_at,created_at FROM \"items\" ORDER BY id,job_id,title,published_at,created_at ASC;"
	rows, err := q.db.WQuery(ctx, "querytest.Dump", sql)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Item
	for rows.Next() {
		var v Item
		if err := rows.Scan(&v.ID, &v.JobID, &v.Title, &v.PublishedAt, &v.CreatedAt); err != nil {
			return nil, err
		}
		for _, applyBeforeDump := range beforeDump {
			applyBeforeDump(&v)
		}
		items = append(items, v)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	bytes, err := json.MarshalIndent(items, "", "  ")
	if err != nil {
		return nil, err
	}
	return bytes, nil
}

func (q *Queries) Load(ctx context.Context, data []byte) error {
	sql := "INSERT INTO \"items\" (id,job_id,title,published_at,created_at) VALUES ($1,$2,$3,$4,$5);"
	rows := make([]Item, 0)
	err := json.Unmarshal(data, &rows)
	if err != nil {
		return err
	}
	for _, row := range rows {
		_, err := q.db.WExec(ctx, "querytest.Load", sql, row.ID, row.JobID, row.Title, row.PublishedAt, row.CreatedAt)
		if err != nil {
			return err
		}
	}
	return nil
}

func hashIfLong(v string) string {
	if len(v) > 64 {
		hash := sha256.Sum256([]byte(v))
		return "h(" + hex.EncodeToString(hash[:]) + ")"
	}
	return v
}

func ptrStr[T any](v *T) string {
	if v == nil {
		return "<nil>"
	}
	return fmt.Sprintf("%+v", *v)
}

// eliminate unused error
var _ = log.Logger
var _ = fmt.Sprintf("")
var _ = time.Now()
var _ = json.RawMessage{}
var _ = sha256.Sum256(nil)
var _ = hex.EncodeToString(nil)
var _ = sync.WaitGroup{}
