// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package compat

import (
	"encoding/json"

	"github.com/google/uuid"
)

type Record struct {
	ID           int64           `json:"id"`
	ExternalID   uuid.UUID       `json:"external_id"`
	OptionalUuid *uuid.UUID      `json:"optional_uuid"`
	Name         string          `json:"display_name"`
	Data         json.RawMessage `json:"data"`
}
