// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package compat

import (
	"context"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"sync"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5"
	"github.com/rs/zerolog/log"
)

const createRecord = `-- name: CreateRecord :exec
INSERT INTO records (id, external_id, optional_uuid, name, data)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, name
`

type CreateRecordParams struct {
	ID           int64
	ExternalID   uuid.UUID
	OptionalUuid *uuid.UUID
	Name         string `json:"display_name"`
	Data         json.RawMessage
}

type CreateRecordRow struct {
	ID   int64
	Name string `json:"display_name"`
}

// -- timeout: 1s
// -- invalidate: [GetRecord]
func (q *Queries) CreateRecord(ctx context.Context, arg CreateRecordParams, getRecord *int64) error {
	qctx, cancel := context.WithTimeout(ctx, time.Millisecond*1000)
	defer cancel()
	_, err := q.db.WExec(qctx, "compat.CreateRecord", createRecord,
		arg.ID,
		arg.ExternalID,
		arg.OptionalUuid,
		arg.Name,
		arg.Data)
	if err != nil {
		return err
	}
	// invalidate
	_ = q.db.PostExec(func() error {
		if q.cache == nil {
			return nil
		}
		anyErr := make(chan error, 1)
		var wg sync.WaitGroup
		wg.Add(1)
		go func() {
			defer wg.Done()
			if getRecord != nil {
				key := "compat:GetRecord:" + hashIfLong(fmt.Sprintf("%+v", (*getRecord)))
				invalidateErr := q.cache.Invalidate(ctx, key)
				if invalidateErr != nil {
					log.Ctx(ctx).Error().Err(invalidateErr).Msgf(
						"Failed to invalidate: %s", key)
					anyErr <- invalidateErr
				}
			}
		}()
		wg.Wait()
		close(anyErr)
		return <-anyErr
	})
	return nil
}

const getRecord = `-- name: GetRecord :one
SELECT id, external_id, optional_uuid, name, data FROM records WHERE id = $1
`

// -- timeout: 1s
// -- cache: 1m
func (q *Queries) GetRecord(ctx context.Context, id int64) (*Record, error) {
	return _GetRecord(ctx, q.AsReadOnly(), id)
}

func (q *ReadOnlyQueries) GetRecord(ctx context.Context, id int64) (*Record, error) {
	return _GetRecord(ctx, q, id)
}

func _GetRecord(ctx context.Context, q CacheQuerierConn, id int64) (*Record, error) {
	qctx, cancel := context.WithTimeout(ctx, time.Millisecond*1000)
	defer cancel()
	q.GetConn().CountIntent("compat.GetRecord")
	dbRead := func() (any, time.Duration, error) {
		cacheDuration := time.Duration(time.Millisecond * 60000)
		row := q.GetConn().WQueryRow(qctx, "compat.GetRecord", getRecord, id)
		var i *Record = new(Record)
		err := row.Scan(
			&i.ID,
			&i.ExternalID,
			&i.OptionalUuid,
			&i.Name,
			&i.Data,
		)
		if err == pgx.ErrNoRows {
			return (*Record)(nil), cacheDuration, nil
		}
		return i, cacheDuration, err
	}
	if q.GetCache() == nil {
		i, _, err := dbRead()
		return i.(*Record), err
	}

	var i *Record
	err := q.GetCache().GetWithTtl(qctx, "compat:GetRecord:"+hashIfLong(fmt.Sprintf("%+v", id)), &i, dbRead, false, false)
	if err != nil {
		return nil, err
	}

	return i, err
}

//// auto generated functions

func (q *Queries) Dump(ctx context.Context, beforeDump ...BeforeDump) ([]byte, error) {
	sql := "SELECT id,external_id,optional_uuid,name,data FROM \"records\" ORDER BY id,name ASC;"
	rows, err := q.db.WQuery(ctx, "compat.Dump", sql)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Record
	for rows.Next() {
		var v Record
		if err := rows.Scan(&v.ID, &v.ExternalID, &v.OptionalUuid, &v.Name, &v.Data); err != nil {
			return nil, err
		}
		for _, applyBeforeDump := range beforeDump {
			applyBeforeDump(&v)
		}
		items = append(items, v)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	bytes, err := json.MarshalIndent(items, "", "  ")
	if err != nil {
		return nil, err
	}
	return bytes, nil
}

func (q *Queries) Load(ctx context.Context, data []byte) error {
	sql := "INSERT INTO \"records\" (id,external_id,optional_uuid,name,data) VALUES ($1,$2,$3,$4,$5);"
	rows := make([]Record, 0)
	err := json.Unmarshal(data, &rows)
	if err != nil {
		return err
	}
	for _, row := range rows {
		_, err := q.db.WExec(ctx, "compat.Load", sql, row.ID, row.ExternalID, row.OptionalUuid, row.Name, row.Data)
		if err != nil {
			return err
		}
	}
	return nil
}

func hashIfLong(v string) string {
	if len(v) > 64 {
		hash := sha256.Sum256([]byte(v))
		return "h(" + hex.EncodeToString(hash[:]) + ")"
	}
	return v
}

func ptrStr[T any](v *T) string {
	if v == nil {
		return "<nil>"
	}
	return fmt.Sprintf("%+v", *v)
}

// eliminate unused error
var _ = log.Logger
var _ = fmt.Sprintf("")
var _ = time.Now()
var _ = json.RawMessage{}
var _ = sha256.Sum256(nil)
var _ = hex.EncodeToString(nil)
var _ = sync.WaitGroup{}
