// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0-70-g644434f9-wicked-fork

package bestsellers

import (
	"time"
)

type Bestseller struct {
	ID          int32      `json:"id"`
	Name        string     `json:"name"`
	Firstbstime *time.Time `json:"firstbstime"`
}
