// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package items

import (
	"context"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgconn"
	"github.com/stumble/wpgx"
)

type WGConn interface {
	WQuery(
		ctx context.Context, name string, unprepared string, args ...interface{}) (pgx.Rows, error)
	WQueryRow(
		ctx context.Context, name string, unprepared string, args ...interface{}) pgx.Row
	WExec(
		ctx context.Context, name string, unprepared string, args ...interface{}) (pgconn.CommandTag, error)
	PostExec(f wpgx.PostExecFunc) error
}

func New(db WGConn) *Queries {
	return &Queries{db: db}
}

type Queries struct {
	db WGConn
}

func (q *Queries) WithTx(tx *wpgx.WTx) *Queries {
	return &Queries{
		db: tx,
	}
}
