// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package revenues

import (
	"encoding/json"
)

type BookRevenue struct {
	ID       int64           `json:"id"`
	Title    string          `json:"title"`
	Metadata json.RawMessage `json:"metadata"`
}
