// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package revenues

import (
	"context"
)

type Querier interface {
	GetRevenue(ctx context.Context, id int64) (*BookRevenue, error)
}

var _ Querier = (*Queries)(nil)
