// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package revenues

import (
	"context"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"sync"
	"time"

	"github.com/jackc/pgx/v5"
	"github.com/rs/zerolog/log"
)

const getRevenue = `-- name: GetRevenue :one
SELECT id, title, metadata FROM book_revenues WHERE id = $1
`

// -- timeout: 250ms
// -- cache: 1m
func (q *Queries) GetRevenue(ctx context.Context, id int64) (*BookRevenue, error) {
	return _GetRevenue(ctx, q.AsReadOnly(), id)
}

func (q *ReadOnlyQueries) GetRevenue(ctx context.Context, id int64) (*BookRevenue, error) {
	return _GetRevenue(ctx, q, id)
}

func _GetRevenue(ctx context.Context, q CacheQuerierConn, id int64) (*BookRevenue, error) {
	qctx, cancel := context.WithTimeout(ctx, time.Millisecond*250)
	defer cancel()
	q.GetConn().CountIntent("revenues.GetRevenue")
	dbRead := func() (any, time.Duration, error) {
		cacheDuration := time.Duration(time.Millisecond * 60000)
		row := q.GetConn().WQueryRow(qctx, "revenues.GetRevenue", getRevenue, id)
		var i *BookRevenue = new(BookRevenue)
		err := row.Scan(&i.ID, &i.Title, &i.Metadata)
		if err == pgx.ErrNoRows {
			return (*BookRevenue)(nil), cacheDuration, nil
		}
		return i, cacheDuration, err
	}
	if q.GetCache() == nil {
		i, _, err := dbRead()
		return i.(*BookRevenue), err
	}

	var i *BookRevenue
	err := q.GetCache().GetWithTtl(qctx, "revenues:GetRevenue:"+hashIfLong(fmt.Sprintf("%+v", id)), &i, dbRead, false, false)
	if err != nil {
		return nil, err
	}

	return i, err
}

//// auto generated functions

func (q *Queries) Dump(ctx context.Context, beforeDump ...BeforeDump) ([]byte, error) {
	sql := "SELECT id,title,metadata FROM \"book_revenues\" ORDER BY id,title ASC;"
	rows, err := q.db.WQuery(ctx, "revenues.Dump", sql)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BookRevenue
	for rows.Next() {
		var v BookRevenue
		if err := rows.Scan(&v.ID, &v.Title, &v.Metadata); err != nil {
			return nil, err
		}
		for _, applyBeforeDump := range beforeDump {
			applyBeforeDump(&v)
		}
		items = append(items, v)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	bytes, err := json.MarshalIndent(items, "", "  ")
	if err != nil {
		return nil, err
	}
	return bytes, nil
}

func (q *Queries) Load(ctx context.Context, data []byte) error {
	sql := "INSERT INTO \"book_revenues\" (id,title,metadata) VALUES ($1,$2,$3);"
	rows := make([]BookRevenue, 0)
	err := json.Unmarshal(data, &rows)
	if err != nil {
		return err
	}
	for _, row := range rows {
		_, err := q.db.WExec(ctx, "revenues.Load", sql, row.ID, row.Title, row.Metadata)
		if err != nil {
			return err
		}
	}
	return nil
}

func hashIfLong(v string) string {
	if len(v) > 64 {
		hash := sha256.Sum256([]byte(v))
		return "h(" + hex.EncodeToString(hash[:]) + ")"
	}
	return v
}

func ptrStr[T any](v *T) string {
	if v == nil {
		return "<nil>"
	}
	return fmt.Sprintf("%+v", *v)
}

// eliminate unused error
var _ = log.Logger
var _ = fmt.Sprintf("")
var _ = time.Now()
var _ = json.RawMessage{}
var _ = sha256.Sum256(nil)
var _ = hex.EncodeToString(nil)
var _ = sync.WaitGroup{}
