// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package users

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	ID        int32
	Name      string
	Metadata  []byte
	Thumbnail string
	Createdat pgtype.Timestamp
}
