// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package orders

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type Itemcategory string

const (
	ItemcategoryALCOHOL   Itemcategory = "ALCOHOL "
	ItemcategoryDRUG      Itemcategory = "DRUG"
	ItemcategoryDRINK     Itemcategory = "DRINK"
	ItemcategoryFRUIT     Itemcategory = "FRUIT"
	ItemcategoryVEGETABLE Itemcategory = "VEGETABLE"
)

func (e *Itemcategory) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Itemcategory(s)
	case string:
		*e = Itemcategory(s)
	default:
		return fmt.Errorf("unsupported scan type for Itemcategory: %T", src)
	}
	return nil
}

type NullItemcategory struct {
	Itemcategory Itemcategory
	Valid        bool // Valid is true if Itemcategory is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullItemcategory) Scan(value interface{}) error {
	if value == nil {
		ns.Itemcategory, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Itemcategory.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullItemcategory) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return ns.Itemcategory, nil
}

type Item struct {
	ID          int64
	Name        string
	Description string
	Category    Itemcategory
	Price       pgtype.Numeric
	Thumbnail   string
	Metadata    []byte
	Createdat   pgtype.Timestamp
	Updatedat   pgtype.Timestamp
}

type ItemsIDLe1000 struct {
	ID          int64
	Name        string
	Description string
	Category    Itemcategory
	Price       pgtype.Numeric
	Thumbnail   string
	Metadata    []byte
	Createdat   pgtype.Timestamp
	Updatedat   pgtype.Timestamp
}

type Order struct {
	ID        int32
	Userid    int32
	Itemid    int32
	Createdat pgtype.Timestamp
	Isdeleted bool
}

type User struct {
	ID        int32
	Name      string
	Metadata  []byte
	Thumbnail string
	Createdat pgtype.Timestamp
}
